Add link Snap.js callback transaction result
Midtrans/technical-documentation-site pull request #88
Opened 2022-08-02 08:02 UTC by Andrenzo17

- update Snap Javascript Callback and add link to Snap Docs.

2022-08-02 10:57 UTC, rizdaprasetya requested changes

2022-08-02 10:57 UTC, rizdaprasetya commented on en/snap/advanced-feature.md
> +
hmm not the most accurate wording & grammar. Should be:
```
For more details on Snap JS callback's result JSON properties & the samples, refer to [this section of Snap Docs](https://snap-docs.midtrans.com/#js-callback)
```

2022-08-02 10:57 UTC, rizdaprasetya commented on en/technical-reference/docs-changelog.md
> +
> update Snap Javascript Callback

That's ambiguous, you are not updating the callback. You are just clarifying the docs. Should be:
> improve Snap JS callback advanced section by adding link to Snap Docs.

2022-08-03 02:46 UTC, Andrenzo17 commented
Thank you for Feedback kak, kindly to review again. 🙏

2022-08-04 05:22 UTC, rizdaprasetya approved these changes
Looks good now, thanks ndre 👍 , will merge

2022-08-04 05:23 UTC, merged